const filmography = [
    {
        id: 1,
        name: 'Como Treinar o Seu Dragão',
        capa: 'C1.png',
        direcao: 'Dean DeBlois / Chris Sanders',
        sinopse: 'Um jovem e desafortunado viking que aspira a caçar dragões se torna o improvável amigo de um jovem dragão, e descobre que pode haver mais nas criaturas do que ele supunha.',
        nota: '8,1/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: 'paramount.png',
        logo2: 'hbo.png',
        logo3: 'globoPlay.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 2,
        name: 'Como Treinar o Seu Dragão 2',
        capa: 'C2.png',
        direcao: 'Dean DeBlois',
        sinopse: 'Quando Soluço e Fúria da Noite descobrem uma caverna de gelo que abriga centenas de novos dragões selvagens e o misterioso Cavaleiro do Dragão, os dois amigos encontram-se no centro de uma batalha para proteger a paz.',
        nota: '7,8/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: 'netflix.png',
        logo2: 'primeVideo.png',
        logo3: 'globoPlay.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 3,
        name: 'Como Treinar o Seu Dragão 3',
        capa: 'C3.png',
        direcao: 'Dean DeBlois',
        sinopse: 'Quando Soluço descobre que Banguela não é o única Fúria da Noite, ele deve procurar por "O Mundo Oculto", antes que um tirano contratado chamado Grimmel o encontre primeiro.',
        nota: '7,4/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 4,
        name: 'As Branquelas',
        capa: 'C4.png',
        direcao: 'Keenen Ivory Wayans',
        sinopse: 'Dois agentes desonestos do FBI vão secretamente proteger as irmãs Wilson, herdeiras de um hotel, de um plano de seqüestro.',
        nota: '5,7/10',
        tag1: 'Comédia',
        tag2: 'Policial',
        logo1: 'netflix.png',
        logo2: 'paramount.png',
        logo3: 'now.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 5,
        name: 'Ponte para Terabítia',
        capa: 'C5.png',
        direcao: 'Gabor Csupo',
        sinopse: 'A vida de um adolescente se complica quando faz amizade com a nova menina na escola, e juntos imaginam um mundo de fantasia completamente novo, para escapar da realidade.',
        nota: '7,2/10',
        tag1: 'Drama',
        tag2: 'Fantasia',
        logo1: 'netflix.png',
        logo2: 'primeVideo.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 6,
        name: 'Clube da Luta',
        capa: 'C6.png',
        direcao: 'David Fincher',
        sinopse: 'Um trabalhador de escritório e um fabricante de sabonetes formam um clube de luta clandestino que evolui para algo muito maior.',
        nota: '8,8/10',
        tag1: 'Drama',
        tag2: '',
        logo1: 'primeVideo.png',
        logo2: 'star+.png',
        logo3: 'hbo.png',
        logo4: 'globoPlay.png',
        logo5: '',
    },
    {
        id: 7,
        name: 'Harry Potter e a Pedra Filosofal',
        capa: 'C7.png',
        direcao: 'Chris Columbus',
        sinopse: 'Uma criança órfã se enrola em uma escola de magia, onde ele aprende a verdade sobre si mesmo, sua família e o terrível mal que se esconde no mundo mágico.',
        nota: '7,6/10',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: 'hbo.png',
        logo2: 'now.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 8,
        name: 'Harry Potter e a Câmara Secreta',
        capa: 'C8.png',
        direcao: 'Chris Columbus',
        sinopse: 'Um mito antigo parece ser corroborado quando uma misteriosa presença começa a perseguir os corredores da escola mágica, deixando suas vítimas petrificadas.',
        nota: '7,4/10',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 9,
        name: 'Harry Potter e o Prisioneiro de Azkaban',
        capa: 'C9.png',
        direcao: 'Alfonso Cuarón',
        sinopse: 'Harry está prestes a começar o seu terceiro ano em Hogwarts quando o terrível assassino Sirius Black, um aliado de Voldemort, foge da prisão de Azkaban. Apesar da vigilância, Harry sabe que, cedo ou tarde, Black virá ao seu encontro.',
        nota: '7,9/10',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: 'hbo.png',
        logo2: 'now.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 10,
        name: 'Harry Potter e o Cálice de Fogo',
        capa: 'C10.png',
        direcao: 'Mike Newell',
        sinopse: 'Um jovem mago entra num perigoso torneio entre escolas de mágia',
        nota: '7,7/10',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: 'hbo.png',
        logo2: 'now.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 11,
        name: 'Harry Potter e a Ordem da Fênix',
        capa: 'C11.png',
        direcao: 'David Yates',
        sinopse: 'Com sua advertência sobre o retorno de Lord Voldemort, Harry e Dumbledore, são atacados pelas autoridades do mago, enquanto um burocrata autoritário toma o poder lentamente em Hogwarts.',
        nota: '7,5/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 12,
        name: 'Harry Potter e o Enigma do Príncipe',
        capa: 'C12.png',
        direcao: 'David Yates',
        sinopse: 'Harry Potter começa seu sexto ano em Hogwarts, descobre um livro "de propriedade do Príncipe Mestiço", e começa a aprender mais sobre o passado sombrio de Voldemort.',
        nota: '7,6/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 13,
        name: 'Harry Potter e as Relíquias da Morte: Parte 1',
        capa: 'C13.png',
        direcao: 'David Yates',
        sinopse: 'Harry embarca em uma corrida contra o tempo para destruir as Horcruxes e descobre a existência dos três objetos mais poderosos do mundo mágico: as relíquias da morte.',
        nota: '7,7/10',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 14,
        name: 'Harry Potter e as Relíquias da Morte: Parte 2',
        capa: 'C14.png',
        direcao: 'David Yates',
        sinopse: 'Harry, Ron e Hermione devem escapar a Voldemort e tentar trabalhar em conjunto para localizar e aniquilar os Horcruxes, que contêm pedaços da alma de Voldemort.',
        nota: '8,1/10',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: 'hbo.png',
        logo2: 'now.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 15,
        name: 'Avatar',
        capa: 'C15.png',
        direcao: 'James Cameron',
        sinopse: 'Um militar paraplégico despachado para a lua Pandora em uma missão única fica dividido entre seguir suas ordens e proteger o mundo que ele sente ser sua casa.',
        nota: '7,9/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: 'disney+.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 16,
        name: 'Avatar: O Caminho da Água',
        capa: 'C16.png',
        direcao: 'James Cameron',
        sinopse: 'Jake Sully vive com sua nova família na lua extrassolar Pandora. Uma vez que uma ameaça familiar retorna para terminar o que foi iniciado anteriormente, Jake deve trabalhar com Neytiri e o exército da raça Na vi para proteger sua casa.',
        nota: '7,7/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 17,
        name: 'Quebrando Regras',
        capa: 'C17.png',
        direcao: 'Jeff Wadlow',
        sinopse: 'Um adolescente frustrado e em conflito chega a uma nova escola, descobre um clube da luta e conhece um colega que começa a coagi-lo para lutar.',
        nota: '6,5/10',
        tag1: 'Ação',
        tag2: 'Drama',
        logo1: 'netflix.png',
        logo2: 'globoPlay.png',
        logo3: 'now.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 18,
        name: 'Quebrando Regras 2',
        capa: 'C18.png',
        direcao: 'Michael Jai White',
        sinopse: 'Quatro lutadores com formações diferentes se juntam para treinar com uma ex-estrela em ascensão do MMA, e no final das contas, precisam lutar entre si.',
        nota: '5,7/10',
        tag1: 'Ação',
        tag2: 'Drama',
        logo1: 'netflix.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 19,
        name: 'Quebrando Regras 3: Nunca Se Rendam',
        capa: 'C19.png',
        direcao: 'Michael Jai White',
        sinopse: 'Retomando depois dos eventos de Quebrando Regras 2, o antigo campeão do MMA Case Walker está na rota de regresso para se sagrou campeão mais uma vez.',
        nota: '6,3/10',
        tag1: 'Ação',
        tag2: 'Esportes',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 20,
        name: 'Shrek',
        capa: 'C20.png',
        direcao: 'Andrew Adamson / Vicky Jenson',
        sinopse: 'Um cavaleiro do mal exila as criaturas de um conto de fadas para o pântano de um ogro rabugento, que em sua ânsia de recuperar seu território faz um pacto para conseguir que uma linda princesa aceda a ser a namorada do cavalheiro.',
        nota: '7,9/10',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 21,
        name: 'Shrek 2',
        capa: 'C21.png',
        direcao: 'Andrew Adamson / Kelly Asbury / Conrad Vernon',
        sinopse: 'Os pais da princesa Fiona convidam ela e Shrek para jantar para celebrar seu casamento, mas eles não sabem que os recém-casados são ogros.',
        nota: '7,3/10',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 22,
        name: 'Shrek Terceiro',
        capa: 'C22.png',
        direcao: 'Chris Miller / Raman Hui',
        sinopse: 'Quando seu sogro adoece, Shrek é considerado o herdeiro de Far, Far Away. Shrek, que não desiste de seu pântano, quer que Artie seja o novo rei. A princesa Fiona, no entanto, reúne umas meninas para se defender do príncipe encantado.',
        nota: '6,1/10',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 23,
        name: 'Shrek para Sempre',
        capa: 'C23.png',
        direcao: 'Mike Mitchell',
        sinopse: 'O Rumpelstiltskin engana um Shrek desgastado para se permitir ser apagado da existência e lançado em uma linha de tempo escura na qual Rumpelstiltskin governa supremamente.',
        nota: '6,3/10',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 24,
        name: 'Questão de Tempo',
        capa: 'C24.png',
        direcao: 'Richard Curtis',
        sinopse: 'Tim descobre que pode viajar no tempo e mudar o que acontece e aconteceu em sua vida. Sua decisão de tornar seu mundo um lugar melhor ao conseguir uma namorada acaba não sendo tão fácil.',
        nota: '7,8/10',
        tag1: 'Drama',
        tag2: 'Fantasia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 25,
        name: 'O Último Mestre do Ar',
        capa: 'C25.png',
        direcao: 'M. Night Shyamalan',
        sinopse: 'Segue as aventuras de Aang, um jovem sucessor de uma longa fila de Avatares, que deve dominar todos os quatro elementos e impedir que a Nação do Fogo escravize as Tribos da Água e o Reino da Terra.',
        nota: '4,0/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 26,
        name: 'Minority Report - A Nova Lei',
        capa: 'C26.png',
        direcao: 'Steven Spielberg',
        sinopse: 'Num futuro em que uma unidade policial especial pode prender assassinos antes de cometer seus crimes, um oficial dessa unidade é acusado de um futuro assassinato.',
        nota: '7,6/10',
        tag1: 'Ação',
        tag2: 'Policial',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 27,
        name: 'Gattaca - A Experiência Genética',
        capa: 'C27.png',
        direcao: 'Andrew Niccol',
        sinopse: 'Um homem assume a identidade de outro para cumprir seu desejo de viajar ao espaço.',
        nota: '7,8/10',
        tag1: 'Drama',
        tag2: 'Ficção Científica',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 28,
        name: 'O Homem de Aço',
        capa: 'C28.png',
        direcao: 'Zack Snyder',
        sinopse: 'Clark Kent é um extraterrestre que foi enviado de seu planeta a Terra para viver uma vida normal. Mas quando sobreviventes de seu planeta invadem a Terra ele deberá revelar-se ao mundo.',
        nota: '7,1/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 29,
        name: 'Batman vs Superman: A Origem da Justiça',
        capa: 'C29.png',
        direcao: 'Zack Snyder',
        sinopse: 'Temeroso das ações do Superman, Batman luta contra o homem de ferro enquanto o mundo decide auql heroi realmente precisam.',
        nota: '6,4/10',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
]