const filmography = [
    {
        id: 1,
        name: 'Como Treinar o Seu Dragão',
        age: '2010',
        duration: '1h 38m',
        capa: 'C1',
        direcao: 'Dean DeBlois / Chris Sanders',
        sinopse: 'Soluço é um jovem viking que não tem capacidade para lutar contra os dragões, como é a tradição local. Sua vida muda quando ele ajuda um dragão que lhe mostra toda a verdade. Juntos, eles tentam provar que dragões e humanos podem ser amigos.',
        nota: '8,1',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: 'paramount.png',
        logo2: 'hbo.png',
        logo3: 'globoPlay.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 2,
        name: 'Como Treinar o Seu Dragão 2',
        age: '2014',
        duration: '1h 42m',
        capa: 'C2',
        direcao: 'Dean DeBlois',
        sinopse: 'Cinco anos se passaram desde que Soluço estabeleceu a paz com os dragões e vive em harmonia, na Ilha de Berk, com Banguela. Eles voam, apostam corridas e se divertem muito. Em uma destas aventuras, descobrem uma caverna secreta cheia de dragões. Agora, a dupla luta para proteger Berk de um guerreiro perigoso, chamado Drago Bludvist, que deseja controlar todos os dragões existentes.',
        nota: '7,8',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: 'netflix.png',
        logo2: 'primeVideo.png',
        logo3: 'globoPlay.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 3,
        name: 'Como Treinar o Seu Dragão 3',
        age: '2019',
        duration: '1h 44m',
        capa: 'C3',
        direcao: 'Dean DeBlois',
        sinopse: 'Soluço busca realizar seu grande sonho de encontrar um lar pacífico onde os dragões possam viver em segurança. Lá, Banguela descobre uma companheira, assim como ele, mas um tanto selvagem. Mas é quando o perigo começa a rondar o lar, que a dupla Banguela e Soluço é testada e precisa tomar decisões difíceis para salvar suas espécies.',
        nota: '7,4',
        tag1: 'infantil',
        tag2: 'fantasia',
        logo1: 'not.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 4,
        name: 'As Branquelas',
        age: '2004',
        duration: '1h 49m',
        capa: 'C4',
        direcao: 'Keenen Ivory Wayans',
        sinopse: 'Dois irmãos agentes do FBI, Marcus e Kevin Copeland, acidentalmente evitam que bandidos sejam presos em uma apreensão de drogas. Como castigo, eles são forçados a escoltar um par de socialites nos Hamptons. Quando as meninas descobrem o plano da agência, elas se recusam a ir. Sem opções, Marcus e Kevin, dois homens negros, decidem fingir que são as irmãs e se transformam em um par de loiras.',
        nota: '5,7',
        tag1: 'comédia',
        tag2: 'policial',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 5,
        name: 'Ponte para Terabítia',
        age: '2007',
        duration: '1h 36m',
        capa: 'C5',
        direcao: 'Gabor Csupo',
        sinopse: 'Jess sente-se um estranho na escola e até mesmo em sua família. Durante todo o verão ele treinou para ser o garoto mais rápido da escola, mas seus planos são ameaçados por Leslie, que vence uma corrida que deveria ser apenas para garotos.',
        nota: '7,2',
        tag1: 'drama',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 6,
        name: 'Clube da Luta',
        age: '1999',
        duration: '2h 19m',
        capa: 'C6',
        direcao: 'David Fincher',
        sinopse: 'Um homem deprimido que sofre de insônia conhece um estranho vendedor chamado Tyler Durden e se vê morando em uma casa suja depois que seu perfeito apartamento é destruído. A dupla forma um clube com regras rígidas onde homens lutam. A parceria perfeita é comprometida quando uma mulher, Marla, atrai a atenção de Tyler.',
        nota: '8,8',
        tag1: 'suspense',
        tag2: 'drama',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/star+.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo4: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo5: '',
    },
    {
        id: 7,
        name: 'Harry Potter e a Pedra Filosofal',
        age: '2001',
        duration: '2h 32m',
        capa: 'C7',
        direcao: 'Chris Columbus',
        sinopse: 'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursleys. Ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente, Harry é impedido de ler a carta por seu tio, mas logo recebe a visita de Hagrid, o guarda-caça de Hogwarts, que chega para levá-lo até a escola. Harry adentra um mundo mágico que jamais imaginara, vivendo diversas aventuras com seus novos amigos, Rony Weasley e Hermione Granger.',
        nota: '7,6',
        tag1: 'aventura',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 8,
        name: 'Harry Potter e a Câmara Secreta',
        age: '2002',
        duration: '2h 41m',
        capa: 'C8',
        direcao: 'Chris Columbus',
        sinopse: 'Após as sofríveis férias na casa dos tios, Harry Potter se prepara para voltar a Hogwarts e começar seu segundo ano na escola de bruxos. Na véspera do início das aulas, a estranha criatura Dobby aparece em seu quarto e o avisa de que voltar é um erro e que algo muito ruim pode acontecer se Harry insistir em continuar os estudos de bruxaria. O garoto, no entanto, está disposto a correr o risco e se livrar do lar problemático.',
        nota: '7,4',
        tag1: 'aventura',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 9,
        name: 'Harry Potter e o Prisioneiro de Azkaban',
        age: '2004',
        duration: '2h 19m',
        capa: 'C9',
        direcao: 'Alfonso Cuarón',
        sinopse: 'É o início do terceiro ano na escola de bruxaria Hogwarts. Harry, Ron e Hermione têm muito o que aprender. Mas uma ameaça ronda a escola e ela se chama Sirius Black. Após doze anos encarcerado na prisão de Azkaban, ele consegue escapar e volta para vingar seu mestre, Lord Voldemort. Para piorar, os Dementores, guardas supostamente enviados para proteger Hogwarts e seguir os passos de Black, parecem ser ameaças ainda mais perigosas.',
        nota: '7,9',
        tag1: 'aventura',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 10,
        name: 'Harry Potter e o Cálice de Fogo',
        age: '2005',
        duration: '2h 37m',
        capa: 'C10',
        direcao: 'Mike Newell',
        sinopse: 'Harry retorna para seu quarto ano na Escola de Magia e Bruxaria de Hogwarts, junto com os seus amigos Ron e Hermione. Desta vez, acontece um torneio entre as três maiores escola de magia, com um participante selecionado de cada escola, pelo Cálice de Fogo. O nome de Harry aparece, mesmo não tendo se inscrito, e ele precisa competir.',
        nota: '7,7',
        tag1: 'aventura',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 11,
        name: 'Harry Potter e a Ordem da Fênix',
        age: '2007',
        duration: '2h 18m',
        capa: 'C11',
        direcao: 'David Yates',
        sinopse: 'Após um verão desastroso, Harry volta para o seu quinto ano em Hogwarts, um dos mais difíceis que terá de encarar. Pouquíssimos alunos e pais acreditam nele ou em Dumbledore sobre a volta de Voldemort, e uma série interminável de artigos circula dizendo que eles estão completamente malucos. Ainda por cima, Dolores Umbridge, a nova professora de Defesa Contra as Artes das Trevas, prova ser a pessoa mais repugnante que Harry já conheceu.',
        nota: '7,5',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 12,
        name: 'Harry Potter e o Enigma do Príncipe',
        age: '2009',
        duration: '2h 33m',
        capa: 'C12',
        direcao: 'David Yates',
        sinopse: 'No sexto ano de Harry em Hogwarts, Lord Voldemort e seus Comensais da Morte estão criando o terror nos mundos bruxo e trouxa. Dumbledore convence seu velho amigo Horácio Slughorn para retornar a Hogwarts como professor de poções após Harry encontrar um estranho livro escolar. Draco Malfoy se esforça para realizar uma ação destinada por Voldemort, enquanto Dumbledore e Harry secretamente trabalham juntos a fim de descobrir o método para destruir o Lorde das Trevas uma vez por todas.',
        nota: '7,6',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 13,
        name: 'Harry Potter e as Relíquias da Morte: Parte 1',
        age: '2010',
        duration: '2h 26m',
        capa: 'C13',
        direcao: 'David Yates',
        sinopse: 'Sem a orientação e proteção de seus professores, Harry, Rony e Hermione iniciam uma missão para destruir as horcruxes, que são as fontes da imortalidade de Voldemort. Embora devam confiar um no outro mais do que nunca, forças das trevas ameaçam separá-los.',
        nota: '7,7',
        tag1: 'aventura',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 14,
        name: 'Harry Potter e as Relíquias da Morte: Parte 2',
        age: '2011',
        duration: '2h 10m',
        capa: 'C14',
        direcao: 'David Yates',
        sinopse: 'A batalha entre as forças do bem e do mal da magia alcançam o mundo dos trouxas. O risco nunca foi tão grande, e ninguém está seguro. Harry Potter precisa fazer um sacrifício final conforme o confronto com Lord Voldemort se aproxima.',
        nota: '8,1',
        tag1: 'aventura',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 15,
        name: 'Avatar',
        age: '2009',
        duration: '2h 42m',
        capa: 'C15',
        direcao: 'James Cameron',
        sinopse: 'No exuberante mundo alienígena de Pandora vivem os Na vi, seres que parecem ser primitivos, mas são altamente evoluídos. Como o ambiente do planeta é tóxico, foram criados os avatares, corpos biológicos controlados pela mente humana que se movimentam livremente em Pandora. Jake Sully, um ex-fuzileiro naval paralítico, volta a andar através de um avatar e se apaixona por uma Na vi. Esta paixão leva Jake a lutar pela sobrevivência de Pandora.',
        nota: '7,9',
        tag1: 'ficção científica',
        tag2: 'ação',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 16,
        name: 'Avatar: O Caminho da Água',
        age: '2022',
        duration: '3h 12m',
        capa: 'C16',
        direcao: 'James Cameron',
        sinopse: 'Após formar uma família, Jake Sully e Ney tiri fazem de tudo para ficarem juntos. No entanto, eles devem sair de casa e explorar as regiões de Pandora quando uma antiga ameaça ressurge, e Jake deve travar uma guerra difícil contra os humanos.',
        nota: '7,7',
        tag1: 'ficção científica',
        tag2: 'ação',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 17,
        name: 'Quebrando Regras',
        age: '2008',
        duration: '1h 55m',
        capa: 'C17',
        direcao: 'Jeff Wadlow',
        sinopse: 'Jake muda-se para Orlando, na Flórida, com sua mãe e o irmão. Ele se sente como um estranho em sua nova escola e frequentemente tem um temperamento fora de controle. Jake quer se encaixar no novo ambiente e decide ir a uma festa com seu colega Baja. Lá, Jake é colocado em uma briga e humilhado. Ao ver o que aconteceu com Jake, outro colega o incentiva a visitar o treinador de artes marciais Jean Roqua.',
        nota: '6,5',
        tag1: 'ação',
        tag2: 'drama',
        logo1: 'netflix.png',
        logo2: 'globoPlay.png',
        logo3: 'now.png',
        logo4: '',
        logo5: '',
    },
    {
        id: 18,
        name: 'Quebrando Regras 2',
        age: '2011',
        duration: '1h 43m',
        capa: 'C18',
        direcao: 'Michael Jai White',
        sinopse: 'O ex-boxeador Zack, os lutadores Tim e Mike e a vítima de bullying Justin compartilham de uma paixão e rapidamente se tornam leais a seu treinador nada tradicional, Case, um brilhante ex-campeão de UFC que passa por um mau momento em sua vida. Ensinando a eles muito mais do que a luta, Case prepara os jovens para uma competição comandada por um universitário e empresário local chamado Max. Quando seu mentor cai em uma armadilha de policiais, os jovens se unem para achar qual deles é o traidor.',
        nota: '5,7',
        tag1: 'ação',
        tag2: 'drama',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 19,
        name: 'Quebrando Regras 3: Nunca Se Rendam',
        age: '2016',
        duration: '1h 42m',
        capa: 'C19',
        direcao: 'Michael Jai White',
        sinopse: 'O ex-campeão de MMA Case Walker tem se mantido longe dos holofotes há muito tempo. Ele agora luta em pequenos torneios locais e ensina os oponentes a aprimorar suas habilidades. Case aceita treinar o velho amigo Brody James, e viaja para a Tailândia, onde logo entra em conflito com o outro treinador de Brody. Para piorar a situação, ele é ridicularizado por trabalhar com Cobra, um lutador arrogante, mas estas complicações só o deixam mais determinado a reconquistar sua glória.',
        nota: '6,3',
        tag1: 'ação',
        tag2: 'drama',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 20,
        name: 'Shrek',
        age: '2001',
        duration: '1h 29m',
        capa: 'C20',
        direcao: 'Andrew Adamson / Vicky Jenson',
        sinopse: 'Um ogro tem sua vida invadida por personagens de contos de fadas que acabam com a tranquilidade de seu lar. Ele faz um acordo pra resgatar uma princesa.',
        nota: '7,9',
        tag1: 'aventura',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 21,
        name: 'Shrek 2',
        age: '2004',
        duration: '1h 45m',
        capa: 'C21',
        direcao: 'Andrew Adamson / Kelly Asbury / Conrad Vernon',
        sinopse: 'Shrek e Fiona acabaram de voltar da lua de mel e vivem felizes em sua casa no pântano. O casal recebe um convite dos pais da princesa, que querem conhecer o novo genro, para um jantar no castelo. Eles ficaram sabendo que Fiona havia se casado com o seu verdadeiro amor, mas o que eles ainda não sabem é que este amor é um ogro mal-educado de mais de 300 quilos, que conta com um burro falante como melhor amigo.',
        nota: '7,3',
        tag1: 'aventura',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 22,
        name: 'Shrek Terceiro',
        age: '2007',
        duration: '1h 33m',
        capa: 'C22',
        direcao: 'Chris Miller / Raman Hui',
        sinopse: 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.',
        nota: '6,1',
        tag1: 'aventura',
        tag2: 'comédia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 23,
        name: 'Shrek para Sempre',
        age: '2010',
        duration: '1h 33m',
        capa: 'C23',
        direcao: 'Mike Mitchell',
        sinopse: 'Há muito tempo ajustado à vida de casado e totalmente domesticado, Shrek fica entediado e começa a ter saudades dos dias em que se sentia um ogro de verdade. Para recuperá-los, ele firma um pacto com Rumpelstiltskin e é levado a um mundo onde ogros são caçados e ele e Fiona nunca se conheceram, além de que seus amigos Burro e Gato de Botas também não o reconhecem. Shrek precisa encontrar um jeito de se livrar do contrato para recuperar sua vida normal e seu grande amor.',
        nota: '6,3',
        tag1: 'aventura',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 24,
        name: 'Questão de Tempo',
        age: '2013',
        duration: '2h 3m',
        capa: 'C24',
        direcao: 'Richard Curtis',
        sinopse: 'Depois de descobrir que ele pode viajar no tempo, o jovem Tim Lake usa sua habilidade para ganhar o coração da mulher dos seus sonhos e salvar seu amigo de um desastre profissional.',
        nota: '7,8',
        tag1: 'drama',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/star+.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 25,
        name: 'O Último Mestre do Ar',
        age: '2010',
        duration: '1h 43m',
        capa: 'C25',
        direcao: 'M. Night Shyamalan',
        sinopse: 'As quatro nações, Ar, Água, Terra e Fogo, viviam em harmonia, até que a nação do Fogo declarou guerra com o objetivo de dominar o mundo. Um século depois, não há perspectiva para o fim da destruição, até que um avatar chamado Aang descobre ter o poder de controlar os quatro elementos. Ele se une aos irmãos Katara e Sokka, da Água, e juntos partem em uma grande e perigosa aventura em busca da paz, para restaurar o equilíbrio e a harmonia.',
        nota: '4,0',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 26,
        name: 'Minority Report - A Nova Lei',
        age: '2002',
        duration: '2h 25m',
        capa: 'C26',
        direcao: 'Steven Spielberg',
        sinopse: 'No ano de 2054, há um sistema que permite que crimes sejam previstos com precisão, o que faz a taxa de assassinatos cair para zero. O problema começa quando o detetive John Anderton, um dos principais agentes do combate ao crime, descobre que foi previsto um assassinato que ele mesmo irá cometer, colocando em dúvida sua reputação e a confiabilidade do sistema.',
        nota: '7,6',
        tag1: 'ação',
        tag2: 'ficção científica',
        logo1: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 27,
        name: 'Gattaca - A Experiência Genética',
        age: '1997',
        duration: '1h 46m',
        capa: 'C27',
        direcao: 'Andrew Niccol',
        sinopse: 'Vincent Freeman sempre sonhou em viajar para o espaço, mas não pode por ser considerado geneticamente inferior. Ele decide desafiar seu destino comprando os genes de Jerome Morrow, e assumindo a sua identidade. Freeman entra para o programa espacial Gattaca e se apaixona por Irene. Uma investigação sobre a morte de um oficial de Gattaca complica os planos de Vincent.',
        nota: '7,8',
        tag1: 'drama',
        tag2: 'ficção científica',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 28,
        name: 'O Homem de Aço',
        age: '2013',
        duration: '2h 23m',
        capa: 'C28',
        direcao: 'Zack Snyder',
        sinopse: 'Com a iminente destruição de Krypton, seu planeta natal, Jor-El e sua mulher procuram preservar a raça enviando o filho recém-nascido para a Terra. A nave espacial da criança aterrissa na fazenda de Jonathan e Martha Kent, que o batizam de Clark e o criam como seu próprio filho. Apesar das habilidades extraordinárias levarem o Clark adulto a viver à margem da sociedade, ele precisa se tornar um herói para salvar aqueles que ama de uma terrível ameaça.',
        nota: '7,1',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 29,
        name: 'Batman vs Superman: A Origem da Justiça',
        age: '2016',
        duration: '2h 31m',
        capa: 'C29',
        direcao: 'Zack Snyder',
        sinopse: 'Temeroso das ações do Superman, Batman luta contra o homem de ferro enquanto o mundo decide auql heroi realmente precisam.',
        nota: '6,4',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 30,
        name: 'Highlander: O Guerreiro Imortal',
        age: '1986',
        duration: '1h 56m',
        capa: 'C30',
        direcao: 'Russell Mulcahy',
        sinopse: 'O místico Russell Nash mata um homem durante uma luta de espadas em um estacionamento de Nova York, mas deixa um pedaço de uma arma antiga alojado em um carro. A especialista em perícias forenses Brenda Wyatt encontra a peça misteriosa e, ao lado de seu parceiro, embarca em uma investigação perigosa sobre uma luta secular entre imortais poderosos.',
        nota: '7,1',
        tag1: 'ação',
        tag2: 'fantasia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 31,
        name: 'Highlander 2: A Ressurreição',
        age: '1991',
        duration: '1h 49m',
        capa: 'C31',
        direcao: 'Russell Mulcahy',
        sinopse: 'Depois de perder sua imortalidade, Connor MacLeod (Christopher Lambert), o último guerreiro highlander, tem agora 75 anos e vive entre os terráqueos. Apesar disso, ele ainda representa uma esperança para o seu povo no planeta Zeist. O poderoso ditador Katana (Michael Ironside) decide matá-lo, iniciando uma batalha mortal. Na luta pela sobrevivência, MacLeod contará com a ajuda do nobre Juan Ramirez (Sean Connery).',
        nota: '4,2',
        tag1: 'fantasia',
        tag2: 'ficção científica',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 32,
        name: 'Mulan',
        age: '2020',
        duration: '1h 55m',
        capa: 'C32',
        direcao: 'Niki Caro',
        sinopse: 'Para salvar seu pai doente de servir no Exército Imperial, uma jovem destemida se disfarça de homem para lutar contra os invasores do norte da China.',
        nota: '5,7',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 33,
        name: 'Mundo Estranho',
        age: '2022',
        duration: '1h 42m',
        capa: 'C33',
        direcao: 'Don Hall',
        sinopse: 'Os Clades são uma família lendária de exploradores cujas diferenças ameaçam derrubar sua missão mais recente e crucial em território desconhecido e traiçoeiro.',
        nota: '5,6',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 34,
        name: 'Eu Sou a Lenda',
        age: '2007',
        duration: '1h 41m',
        capa: 'C34',
        direcao: 'Francis Lawrence',
        sinopse: 'Robert Neville é um brilhante cientista e o único sobrevivente de uma epidemia que transformou os humanos em mutantes sedentos por sangue. Andando pela cidade de Nova York, ele procura por outros possíveis sobreviventes e tenta achar a cura da praga usando seu próprio sangue, que é imune.',
        nota: '7,2',
        tag1: 'ficção científica',
        tag2: 'terror',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 35,
        name: 'Encanto',
        age: '2021',
        duration: '1h 49m',
        capa: 'C35',
        direcao: 'Byron Howard / Jared Bush',
        sinopse: 'Uma menina colombiana pode ser a última esperança de sua família quando descobre que a magia que envolve o Encanto, um lugar que abençoa crianças com dons únicos, está em perigo.',
        nota: '7,2',
        tag1: 'infantil',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 36,
        name: 'Festa no Céu',
        age: '2014',
        duration: '1h 35m',
        capa: 'C36',
        direcao: 'Jorge R. Gutierrez',
        sinopse: 'Em San Angel, no México, viviam Manolo, Maria e Joaquim, amigos desde a infância. Mesmo que suas vidas tenham tomado rumos diferentes - Maria foi para Europa, Joaquim ingressou na vida militar e Manolo se dedicou para ser toureiro - algo continuou igual: os dois ainda são apaixonados por Maria. Dividido entre cumprir as expectativas de sua família e seguir seu coração, Manolo viaja em mundos fantásticos e enfrenta seus maiores medos.',
        nota: '7,2',
        tag1: 'infantil',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 37,
        name: 'Divertida Mente',
        age: '2015',
        duration: '1h 35m',
        capa: 'C37',
        direcao: 'Pete Docter',
        sinopse: 'Com a mudança para uma nova cidade, as emoções de Riley, que tem apenas 11 anos de idade, ficam extremamente agitadas. Uma confusão na sala de controle do seu cérebro deixa a Alegria e a Tristeza de fora, afetando a vida de Riley radicalmente.',
        nota: '8,1',
        tag1: 'infantil',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 38,
        name: 'Soul',
        age: '2020',
        duration: '1h 40',
        capa: 'C38',
        direcao: 'Pete Docter',
        sinopse: 'Joe é um professor de música do ensino médio apaixonado por jazz, cuja vida não foi como ele esperava. Quando ele viaja a uma outra realidade para ajudar outra pessoa a encontrar sua paixão, ele descobre o verdadeiro sentido da vida.',
        nota: '8,0',
        tag1: 'infantil',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 39,
        name: 'Toy Story 3',
        age: '2010',
        duration: '1h 43m',
        capa: 'C39',
        direcao: 'Lee Unkrich',
        sinopse: 'Com seu amado Andy se preparando para ir para a universidade, Woody, Buzz Lightyear e o restante dos brinquedos enfrentam o seu maior medo: serem esquecidos quando são colocados no sótão. Mas, por engano, acabam no meio-fio. Woody, o único escolhido para acompanhar Andy, percebe o erro e salva a gangue, mas os brinquedos acabam em uma creche. Lá, todos percebem que existe um lugar com brincadeiras infinitas, mas os pequenos são incontroláveis e Woody e sua turma decidem planejar uma grande fuga.',
        nota: '8,3',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 40,
        name: 'Toy Story 4',
        age: '2019',
        duration: '1h 40m',
        capa: 'C40',
        direcao: 'Josh Cooley',
        sinopse: 'Woody, Buzz Lightyear e o resto da turma embarcam em uma viagem com Bonnie e um novo brinquedo chamado Forky. A aventura logo se transforma em uma reunião inesperada quando o ligeiro desvio que Woody faz o leva ao seu amigo há muito perdido, Bo Peep.',
        nota: '7,7',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 41,
        name: 'Lightyear',
        age: '2022',
        duration: '1h 45m',
        capa: 'C41',
        direcao: 'Angus MacLane',
        sinopse: 'O lendário Buzz Lightyear e sua tripulação cumprem a missão mais difícil de todas até agora. Eles devem aprender a trabalhar juntos para escaparem do malvado Zurg e de seu exército de robôs.',
        nota: '6,1',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 42,
        name: 'WALL-E',
        age: '2008',
        duration: '1h 38m',
        capa: 'C42',
        direcao: 'Andrew Stanton',
        sinopse: 'Após entulhar a Terra de lixo e poluir a atmosfera com gases tóxicos, a humanidade deixou o planeta e passou a viver em uma gigantesca nave. O plano era que o retiro durasse alguns poucos anos, com robôs sendo deixados para limpar o planeta. WALL-E é o último destes robôs, e sua vida consiste em compactar o lixo existente no planeta. Até que um dia surge repentinamente uma nave, que traz um novo e moderno robô: Eva. A princípio curioso, WALL-E se apaixona e resolve segui-la por toda a galáxia.',
        nota: '8,4',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 43,
        name: 'Operação Big Hero',
        age: '2014',
        duration: '1h 45m',
        capa: 'C43',
        direcao: 'Chris Williams / Don Hall',
        sinopse: 'O grande robô inflável está sempre a postos para cuidar de Hiro Hamada. Quando algo devastador assola a cidade, o menino prodígio, seus amigos e o robô formam um grupo de heróis para combater o mal.',
        nota: '7,8',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 44,
        name: 'LEGO Batman: O Filme',
        age: '2017',
        duration: '1h 44m',
        capa: 'C44',
        direcao: 'Chris McKay',
        sinopse: 'Batman descobre que acidentalmente adotou um garoto órfão, que se torna ninguém menos que Robin. A dupla formada pelo arrogante Homem-Morcego e o empolgado ajudante deve combater o crime e prender o Coringa.',
        nota: '7,3',
        tag1: 'ação',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 45,
        name: 'uma aventura lego',
        age: '2014',
        duration: '1h 40m',
        capa: 'C45',
        direcao: 'Phil Lord / Chris Miller',
        sinopse: 'Emmet é uma minifigura LEGO perfeitamente comum e seguidora das regras, que é erroneamente identificado como uma pessoa extraordinária, essencial para salvar o mundo. Ele é recrutado por uma irmandade de estranhos para uma jornada épica com a finalidade de deter um tirano, uma viagem para a qual Emmet está totalmente despreparado. Como companheiros dessa aventura, ele terá Vitrúvius, um velho místico, e a durona Lucy, que convoca o misterioso Batman, com quem compartilha uma história do passado.',
        nota: '7,7',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 46,
        name: 'Atlantis - O Reino Perdido',
        age: '2001',
        duration: '1h 35m',
        capa: 'C46',
        direcao: 'Kirk Wise / Gary Trousdale',
        sinopse: 'Um cartógrafo e linguista chamado Milo Thatch encontra um antigo manuscrito no qual há supostamente pistas de como chegar em Atlantis, o mítico continente perdido no fundo do mar. Ao lado de uma equipe de especialistas liderada pelo Comandante Rourke, ele embarca no submarino Ulysses para comprovar que a lenda é real.',
        nota: '6,9',
        tag1: 'aventura',
        tag2: 'infantil',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 47,
        name: 'Desencantada',
        age: '2022',
        duration: '1h 58m',
        capa: 'C47',
        direcao: 'Adam Shankman',
        sinopse: 'Anos depois de seu felizes para sempre, Giselle, Robert e Morgan se mudam para uma nova comunidade, mas acabam por desequilibrar Andalasia e o mundo real.',
        nota: '5,6',
        tag1: 'musical',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 48,
        name: 'Tico e Teco: Defensores da Lei',
        age: '2022',
        duration: '1h 37m',
        capa: 'C48',
        direcao: 'Akiva Schaffer',
        sinopse: 'Tico e Teco vivem entre desenhos animados e humanos na Los Angeles moderna, mas suas vidas são bem diferentes agora. Um dia, um ex-colega de elenco desaparece misteriosamente, então a dupla precisa reparar sua amizade quebrada e salvar o amigo.',
        nota: '7,0',
        tag1: 'aventura',
        tag2: 'comédia',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 49,
        name: 'Cruella',
        age: '2021',
        duration: '2h 14m',
        capa: 'C49',
        direcao: 'Craig Gillespie',
        sinopse: 'Inteligente, criativa e determinada, Estella quer fazer um nome para si através de seus designs e acaba chamando a atenção da Baronesa Von Hellman. Entretanto, o relacionamento delas desencadeia um curso de eventos e revelações que fazem com que Estella abrace seu lado rebelde e se torne a Cruella, uma pessoa má, elegante e voltada para a vingança.',
        nota: '7,3',
        tag1: 'comédia',
        tag2: 'drama',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 50,
        name: 'A Dama e o Vagabundo',
        age: '2019',
        duration: '1h 16m',
        capa: 'C50',
        direcao: 'Wilfred Jackson / Clyde Geronimi / Hamilton Luske',
        sinopse: 'Este clássico animado da Disney mostra uma cadela mimada chamada Lady e o término de sua vida confortável quando seus donos têm um bebê. Depois de algumas circunstâncias tensas, Lady encontra-se solta na rua, fazendo amizade. Ela torna-se protegida do vira-lata durão Tramp e um romance começa a florescer entre os dois cães.',
        nota: '6,2',
        tag1: 'musical',
        tag2: 'infantil',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 51,
        name: 'Up: Altas Aventuras',
        age: '2009',
        duration: '1h 36m',
        capa: 'C51',
        direcao: 'Pete Docter',
        sinopse: 'Carl Fredricksen é um vendedor de balões que, aos 78 anos, está prestes a perder a casa em que sempre viveu com sua esposa, a falecida Ellie. Após um incidente, Carl é considerado uma ameaça pública e forçado a ser internado. Para evitar que isto aconteça, ele põe balões em sua casa, fazendo com que ela levante voo. Carl quer viajar para uma floresta na América do Sul, onde ele e Ellie sempre desejaram morar, mas descobre que um problema embarcou junto: Russell, um menino de 8 anos.',
        nota: '8,3',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 52,
        name: 'Luca',
        age: '2021',
        duration: '1h 36m',
        capa: 'C52',
        direcao: 'Enrico Casarosa',
        sinopse: 'Luca vive aventuras com seu novo melhor amigo, mas a diversão é ameaçada por um segredo: seu amigo é um monstro marinho de outro mundo que fica abaixo da superfície da água.',
        nota: '7,5',
        tag1: 'comédia',
        tag2: 'fantasia',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 53,
        name: 'Dois Irmãos: Uma Jornada Fantástica',
        age: '2020',
        duration: '1h 42m',
        capa: 'C53',
        direcao: 'Dan Scanlon',
        sinopse: 'Em um mundo transformado, no qual as criaturas não dependiam mais da magia para viver, dois irmãos elfos recebem um cajado de bruxo de seu falecido pai, capaz de trazê-lo de volta à vida. Inexperientes com qualquer tipo de magia, Ian e Barley não conseguem executar o feitiço e acabam gerando uma criatura sem cabeça. Para passar mais um dia com seu pai, eles embarcam em uma jornada fantástica. Ao perceber a ausência dos filhos, sua mãe se une à uma lendária manticora para encontrá-los.',
        nota: '7,4',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 54,
        name: 'Viva: A Vida é uma Festa',
        age: '2017',
        duration: '1h 45m',
        capa: 'C54',
        direcao: 'Adrian Molina / Lee Unkrich',
        sinopse: 'Apesar da proibição da música por gerações de sua família, o jovem Miguel sonha em se tornar um músico talentoso como seu ídolo Ernesto de la Cruz. Desesperado para provar seu talento, Miguel se encontra na deslumbrante e colorida Terra dos Mortos. Depois de conhecer um charmoso malandro chamado Héctor, os dois novos amigos embarcam em uma jornada extraordinária para desvendar a verdadeira história por trás da história da família de Miguel.',
        nota: '8,4',
        tag1: 'infantil',
        tag2: 'comédia',
        logo1: 'disney+.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 55,
        name: 'Procurando Dory',
        age: '2016',
        duration: '1h 37m',
        capa: 'C55',
        direcao: 'Andrew Stanton',
        sinopse: 'Um ano após ajudar Marlin a reencontrar seu filho Nemo, Dory relembra sua amada família. Com saudades, decide fazer de tudo para reencontrá-los. Ela acaba esbarrando com amigos do passado e cai nas perigosas mãos dos humanos.',
        nota: '7,3',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: 'disney+.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 56,
        name: 'Ted',
        age: '2012',
        duration: '1h 46m',
        capa: 'C56',
        direcao: 'Seth MacFarlane',
        sinopse: 'Quando criança, John desejou que seu ursinho Ted ganhasse vida e, surpreendentemente, foi atendido. Porém, agora que é adulto, ele precisa lidar com as consequências de seu pedido, já que Ted não vai parar de atormentar a sua vida.',
        nota: '6,9',
        tag1: 'comédia',
        tag2: 'fantasia',
        logo1: 'primeVideo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 57,
        name: 'Ted 2',
        age: '2015',
        duration: '1h 56m',
        capa: 'C57',
        direcao: 'Seth MacFarlane',
        sinopse: 'O urso de pelúcia Ted casa-se com Tami-Lynn. O casal pretende ter um bebê, mas para terem direito à inseminação artificial, Ted tem que provar na justiça que é um ser humano. Para alcançar o seu sonho, ele conta com a ajuda da advogada Samantha e do seu grande amigo John.',
        nota: '6,3',
        tag1: 'comédia',
        tag2: 'fantasia',
        logo1: 'primeVideo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 58,
        name: '2001 - Uma Odisseia no Espaço',
        age: '1968',
        duration: '2h 19m',
        capa: 'C58',
        direcao: 'Stanley Kubrick',
        sinopse: 'Uma estrutura imponente preta fornece uma conexão entre o passado e o futuro nesta adaptação enigmática de um conto reverenciado de ficção científica do autor Arthur C. Clarke. Quando o Dr. Dave Bowman e outros astronautas são enviados para uma misteriosa missão, os chips de seus computadores começam a mostrar um comportamento estranho, levando a um tenso confronto entre homem e máquina que resulta em uma viagem alucinante no espaço e no tempo.',
        nota: '8,3',
        tag1: 'ficção científica',
        tag2: 'drama',
        logo1: 'hbo.png',
        logo2: 'now.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 59,
        name: 'Blade Runner - O Caçador de Androides',
        age: '1962',
        duration: '1h 57m',
        capa: 'C59',
        direcao: 'Ridley Scott',
        sinopse: 'No século 21, uma corporação desenvolve clones humanos para serem usados como escravos em colônias fora da Terra, identificados como replicantes. Em 2019, um ex-policial é acionado para caçar um grupo fugitivo vivendo disfarçado em Los Angeles.',
        nota: '8,1',
        tag1: 'ficção científica',
        tag2: 'ação',
        logo1: 'hbo.png',
        logo2: 'now.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 60,
        name: 'Blade Runner 2049',
        age: '2017',
        duration: '2h 43m',
        capa: 'C60',
        direcao: 'Denis Villeneuve',
        sinopse: 'Após descobrir um segredo que ameaça o que resta da sociedade, um novo policial parte em busca de Rick Deckard, que está desaparecido há 30 anos.',
        nota: '8,0',
        tag1: 'ficção científica',
        tag2: 'ação',
        logo1: 'netflix.png',
        logo2: 'paramount.png',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 61,
        name: 'Blade - O Caçador de Vampiros',
        age: '1998',
        duration: '2h',
        capa: 'C61',
        direcao: 'Stephen Norrington',
        sinopse: 'O herói Blade , metade mortal e metade imortal, parte em busca do vampiro responsável pela morte de sua mãe. Blade quer eliminá-lo do mundo dos vampiros e em um mundo tecnologicamente avançado, Blade lutará para capturar aquele que quer destruir a vida humana.',
        nota: '7,1',
        tag1: 'ação',
        tag2: 'terror',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 62,
        name: 'Blade 2',
        age: '2002',
        duration: '1h 57m',
        capa: 'C62',
        direcao: 'Guillermo del Toro',
        sinopse: 'Direto das páginas do Marvel Comics vem a emocionante continuação de Blade, Blade II: O Caçador de Vampiros, que é consumido pelo desejo de vingar a maldição de seu nascimento e salvar a raça humana de um Armagedon sangrento. Nesta nova aventura cheia de ação, Blade é forçado a se juntar com os vampiros a fim de superar um novo tipo de monstro que ameaça eliminar ambas as raças.',
        nota: '6,7',
        tag1: 'ação',
        tag2: 'terror',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 63,
        name: 'Blade Trinity',
        age: '2004',
        duration: '2h 3m',
        capa: 'C63',
        direcao: 'David S. Goyer',
        sinopse: 'A guerra entre humanos e vampiros continua, mas a melhor esperança dos humanos, o meio-vampiro Blade, foi acusado de vários assassinatos e, agora, a opinião pública está contra ele. O responsável pela publicidade negativa de Blade é Danica Talos, que está determinada a vencer. Agora Blade precisa aliar-se aos caçadores de vampiros para salvar a humanidade.',
        nota: '5,8',
        tag1: 'ação',
        tag2: 'terror',
        logo1: 'hbo.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 64,
        name: 'Universidade Monstros',
        age: '2013',
        duration: '1h 44m',
        capa: 'C64',
        direcao: 'Dan Scanlon',
        sinopse: 'Mike e Sulley, alunos promissores da Universidade Monstros, são forçados a se unirem quando sua disputa acirrada pelo posto de aluno mais assustador da turma foge ao controle e eles acabam sendo expulsos da faculdade.',
        nota: '7,2',
        tag1: 'infantil',
        tag2: 'comédia',
        logo1: 'disney+.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 65,
        name: 'Monstros S.A.',
        age: '2001',
        duration: '1h 32m',
        capa: 'C65',
        direcao: 'Pete Docter',
        sinopse: 'A maior fábrica de monstros do mundo conta com James Sullivan, um dos monstros mais assustadores, que tem o pelo azul e chifres, além de seu assistente e melhor amigo Mike, um monstro verde de um olho só. Eles têm por missão assustar as crianças, que são consideradas tóxicas pelos monstros e cujo contato com eles seria catastrófico para seu mundo. Porém, ao visitar o mundo dos humanos a trabalho, Mike e Sully conhecem a garota Boo, que acaba sem querer indo parar no mundo dos monstros.',
        nota: '8,1',
        tag1: 'comédia',
        tag2: 'aventura',
        logo1: 'disney+.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 66,
        name: 'Procurando Nemo',
        age: '2003',
        duration: '1h 40m',
        capa: 'C66',
        direcao: 'Andrew Stanton',
        sinopse: 'Em seu primeiro dia de aula, esquecendo os conselhos do pai superprotetor, Nemo é capturado por um mergulhador e acaba no aquário de um dentista. Enquanto Nemo tenta bolar um plano para escapar, seu pai cruza o oceano para resgatá-lo.',
        nota: '8,1',
        tag1: 'infantil',
        tag2: 'aventura',
        logo1: 'disney+.png',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    
];

const listContainer = document.querySelector("#container");

function render(filmography){
    let list = '';

    if(filmography.length <= 0){
        list += `<div id="no-project">Nenhum filme encontrado</div>`
    }else{
        filmography.forEach((cod, index) =>{
            list+= `
                <div class="card">
                    <div class="front">
                        <div class="poster">
                            <img src="./assets/img/capas/${cod.capa}.png" alt="">
                        </div>
                    </div>
                   
                    <div class="back">
                        <div class="details">
                                <h2>Direção: ${cod.name}</h2>
                                <h3>Direção: ${cod.direcao}</h3>
                                <div class="rating">
                                    <i class="fa-solid fa-star"></i>
                                    <span>${cod.nota}/10 IMDb</span>
                                </div>
                                <div class="ageAndTime">
                                    <p>${cod.age} - ${cod.duration}</p>
                                </div>
                                <div class="tags">
                                    <span class="${cod.tag1}">${cod.tag1}</span>
                                    <span class="${cod.tag2}">${cod.tag2}</span>
                                </div>
                                <div class="sinopse">
                                    <p>${cod.sinopse}</p>
                                </div>
                                <div class="streaming">
                                    <h4>Onde assistir?</h4>
                                    <ul>
                                        <li><img src="./assets/img/logos/${cod.logo1}" alt=""></li>
                                        <li><img src="./assets/img/logos/${cod.logo2}" alt=""></li>
                                        <li><img src="./assets/img/logos/${cod.logo3}" alt=""></li>
                                        <li><img src="./assets/img/logos/${cod.logo4}" alt=""></li>
                                        <li><img src="./assets/img/logos/${cod.logo5}" alt=""></li>
                                    </ul>
                                </div>
                        </div>
                    </div>
                </div>
            `
        })
    }

    listContainer.innerHTML = list;
};

render(filmography);