const filmography = [
    {
        id: 1,
        name: 'Como Treinar o Seu Dragão',
        capa: 'C1',
        direcao: 'Dean DeBlois / Chris Sanders',
        sinopse: 'Um jovem e desafortunado viking que aspira a caçar dragões se torna o improvável amigo de um jovem dragão, e descobre que pode haver mais nas criaturas do que ele supunha.',
        nota: '8,1',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 2,
        name: 'Como Treinar o Seu Dragão 2',
        capa: 'C2',
        direcao: 'Dean DeBlois',
        sinopse: 'Quando Soluço e Fúria da Noite descobrem uma caverna de gelo que abriga centenas de novos dragões selvagens e o misterioso Cavaleiro do Dragão, os dois amigos encontram-se no centro de uma batalha para proteger a paz.',
        nota: '7,8',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 3,
        name: 'Como Treinar o Seu Dragão 3',
        capa: 'C3',
        direcao: 'Dean DeBlois',
        sinopse: 'Quando Soluço descobre que Banguela não é o única Fúria da Noite, ele deve procurar por "O Mundo Oculto", antes que um tirano contratado chamado Grimmel o encontre primeiro.',
        nota: '7,4',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 4,
        name: 'As Branquelas',
        capa: 'C4',
        direcao: 'Keenen Ivory Wayans',
        sinopse: 'Dois agentes desonestos do FBI vão secretamente proteger as irmãs Wilson, herdeiras de um hotel, de um plano de seqüestro.',
        nota: '5,7',
        tag1: 'Comédia',
        tag2: 'Policial',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 5,
        name: 'Ponte para Terabítia',
        capa: 'C5',
        direcao: 'Gabor Csupo',
        sinopse: 'A vida de um adolescente se complica quando faz amizade com a nova menina na escola, e juntos imaginam um mundo de fantasia completamente novo, para escapar da realidade.',
        nota: '7,2',
        tag1: 'Drama',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 6,
        name: 'Clube da Luta',
        capa: 'C6',
        direcao: 'David Fincher',
        sinopse: 'Um trabalhador de escritório e um fabricante de sabonetes formam um clube de luta clandestino que evolui para algo muito maior.',
        nota: '8,8',
        tag1: 'Drama',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/star+.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo4: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo5: '',
    },
    {
        id: 7,
        name: 'Harry Potter e a Pedra Filosofal',
        capa: 'C7',
        direcao: 'Chris Columbus',
        sinopse: 'Uma criança órfã se enrola em uma escola de magia, onde ele aprende a verdade sobre si mesmo, sua família e o terrível mal que se esconde no mundo mágico.',
        nota: '7,6',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 8,
        name: 'Harry Potter e a Câmara Secreta',
        capa: 'C8',
        direcao: 'Chris Columbus',
        sinopse: 'Um mito antigo parece ser corroborado quando uma misteriosa presença começa a perseguir os corredores da escola mágica, deixando suas vítimas petrificadas.',
        nota: '7,4',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 9,
        name: 'Harry Potter e o Prisioneiro de Azkaban',
        capa: 'C9',
        direcao: 'Alfonso Cuarón',
        sinopse: 'Harry está prestes a começar o seu terceiro ano em Hogwarts quando o terrível assassino Sirius Black, um aliado de Voldemort, foge da prisão de Azkaban. Apesar da vigilância, Harry sabe que, cedo ou tarde, Black virá ao seu encontro.',
        nota: '7,9',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 10,
        name: 'Harry Potter e o Cálice de Fogo',
        capa: 'C10',
        direcao: 'Mike Newell',
        sinopse: 'Um jovem mago entra num perigoso torneio entre escolas de mágia',
        nota: '7,7',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 11,
        name: 'Harry Potter e a Ordem da Fênix',
        capa: 'C11',
        direcao: 'David Yates',
        sinopse: 'Com sua advertência sobre o retorno de Lord Voldemort, Harry e Dumbledore, são atacados pelas autoridades do mago, enquanto um burocrata autoritário toma o poder lentamente em Hogwarts.',
        nota: '7,5',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 12,
        name: 'Harry Potter e o Enigma do Príncipe',
        capa: 'C12',
        direcao: 'David Yates',
        sinopse: 'Harry Potter começa seu sexto ano em Hogwarts, descobre um livro "de propriedade do Príncipe Mestiço", e começa a aprender mais sobre o passado sombrio de Voldemort.',
        nota: '7,6',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 13,
        name: 'Harry Potter e as Relíquias da Morte: Parte 1',
        capa: 'C13',
        direcao: 'David Yates',
        sinopse: 'Harry embarca em uma corrida contra o tempo para destruir as Horcruxes e descobre a existência dos três objetos mais poderosos do mundo mágico: as relíquias da morte.',
        nota: '7,7',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 14,
        name: 'Harry Potter e as Relíquias da Morte: Parte 2',
        capa: 'C14',
        direcao: 'David Yates',
        sinopse: 'Harry, Ron e Hermione devem escapar a Voldemort e tentar trabalhar em conjunto para localizar e aniquilar os Horcruxes, que contêm pedaços da alma de Voldemort.',
        nota: '8,1',
        tag1: 'Aventura',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 15,
        name: 'Avatar',
        capa: 'C15',
        direcao: 'James Cameron',
        sinopse: 'Um militar paraplégico despachado para a lua Pandora em uma missão única fica dividido entre seguir suas ordens e proteger o mundo que ele sente ser sua casa.',
        nota: '7,9',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/disney+.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 16,
        name: 'Avatar: O Caminho da Água',
        capa: 'C16',
        direcao: 'James Cameron',
        sinopse: 'Jake Sully vive com sua nova família na lua extrassolar Pandora. Uma vez que uma ameaça familiar retorna para terminar o que foi iniciado anteriormente, Jake deve trabalhar com Neytiri e o exército da raça Na vi para proteger sua casa.',
        nota: '7,7',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 17,
        name: 'Quebrando Regras',
        capa: 'C17',
        direcao: 'Jeff Wadlow',
        sinopse: 'Um adolescente frustrado e em conflito chega a uma nova escola, descobre um clube da luta e conhece um colega que começa a coagi-lo para lutar.',
        nota: '6,5',
        tag1: 'Ação',
        tag2: 'Drama',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 18,
        name: 'Quebrando Regras 2',
        capa: 'C18',
        direcao: 'Michael Jai White',
        sinopse: 'Quatro lutadores com formações diferentes se juntam para treinar com uma ex-estrela em ascensão do MMA, e no final das contas, precisam lutar entre si.',
        nota: '5,7',
        tag1: 'Ação',
        tag2: 'Drama',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 19,
        name: 'Quebrando Regras 3: Nunca Se Rendam',
        capa: 'C19',
        direcao: 'Michael Jai White',
        sinopse: 'Retomando depois dos eventos de Quebrando Regras 2, o antigo campeão do MMA Case Walker está na rota de regresso para se sagrou campeão mais uma vez.',
        nota: '6,3',
        tag1: 'Ação',
        tag2: 'Esportes',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 20,
        name: 'Shrek',
        capa: 'C20',
        direcao: 'Andrew Adamson / Vicky Jenson',
        sinopse: 'Um cavaleiro do mal exila as criaturas de um conto de fadas para o pântano de um ogro rabugento, que em sua ânsia de recuperar seu território faz um pacto para conseguir que uma linda princesa aceda a ser a namorada do cavalheiro.',
        nota: '7,9',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 21,
        name: 'Shrek 2',
        capa: 'C21',
        direcao: 'Andrew Adamson / Kelly Asbury / Conrad Vernon',
        sinopse: 'Os pais da princesa Fiona convidam ela e Shrek para jantar para celebrar seu casamento, mas eles não sabem que os recém-casados são ogros.',
        nota: '7,3',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 22,
        name: 'Shrek Terceiro',
        capa: 'C22',
        direcao: 'Chris Miller / Raman Hui',
        sinopse: 'Quando seu sogro adoece, Shrek é considerado o herdeiro de Far, Far Away. Shrek, que não desiste de seu pântano, quer que Artie seja o novo rei. A princesa Fiona, no entanto, reúne umas meninas para se defender do príncipe encantado.',
        nota: '6,1',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 23,
        name: 'Shrek para Sempre',
        capa: 'C23',
        direcao: 'Mike Mitchell',
        sinopse: 'O Rumpelstiltskin engana um Shrek desgastado para se permitir ser apagado da existência e lançado em uma linha de tempo escura na qual Rumpelstiltskin governa supremamente.',
        nota: '6,3',
        tag1: 'Aventura',
        tag2: 'Comédia',
        logo1: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 24,
        name: 'Questão de Tempo',
        capa: 'C24',
        direcao: 'Richard Curtis',
        sinopse: 'Tim descobre que pode viajar no tempo e mudar o que acontece e aconteceu em sua vida. Sua decisão de tornar seu mundo um lugar melhor ao conseguir uma namorada acaba não sendo tão fácil.',
        nota: '7,8',
        tag1: 'Drama',
        tag2: 'Fantasia',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/star+.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/globoPlay.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 25,
        name: 'O Último Mestre do Ar',
        capa: 'C25',
        direcao: 'M. Night Shyamalan',
        sinopse: 'Segue as aventuras de Aang, um jovem sucessor de uma longa fila de Avatares, que deve dominar todos os quatro elementos e impedir que a Nação do Fogo escravize as Tribos da Água e o Reino da Terra.',
        nota: '4,0',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/netflix.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 26,
        name: 'Minority Report - A Nova Lei',
        capa: 'C26',
        direcao: 'Steven Spielberg',
        sinopse: 'Num futuro em que uma unidade policial especial pode prender assassinos antes de cometer seus crimes, um oficial dessa unidade é acusado de um futuro assassinato.',
        nota: '7,6',
        tag1: 'Ação',
        tag2: 'Policial',
        logo1: '<li><img src="./assets/img/logos/paramount.png" alt=""></li>',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 27,
        name: 'Gattaca - A Experiência Genética',
        capa: 'C27',
        direcao: 'Andrew Niccol',
        sinopse: 'Um homem assume a identidade de outro para cumprir seu desejo de viajar ao espaço.',
        nota: '7,8',
        tag1: 'Drama',
        tag2: 'Ficção Científica',
        logo1: '',
        logo2: '',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 28,
        name: 'O Homem de Aço',
        capa: 'C28',
        direcao: 'Zack Snyder',
        sinopse: 'Clark Kent é um extraterrestre que foi enviado de seu planeta a Terra para viver uma vida normal. Mas quando sobreviventes de seu planeta invadem a Terra ele deberá revelar-se ao mundo.',
        nota: '7,1',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/primeVideo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo3: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo4: '',
        logo5: '',
    },
    {
        id: 29,
        name: 'Batman vs Superman: A Origem da Justiça',
        capa: 'C29',
        direcao: 'Zack Snyder',
        sinopse: 'Temeroso das ações do Superman, Batman luta contra o homem de ferro enquanto o mundo decide auql heroi realmente precisam.',
        nota: '6,4',
        tag1: 'Ação',
        tag2: 'Aventura',
        logo1: '<li><img src="./assets/img/logos/hbo.png" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/now.png" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 30,
        name: '',
        capa: 'C30',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 31,
        name: '',
        capa: 'C31',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 32,
        name: '',
        capa: 'C32',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 33,
        name: '',
        capa: 'C33',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 34,
        name: '',
        capa: 'C34',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 35,
        name: '',
        capa: 'C35',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 36,
        name: '',
        capa: 'C36',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 37,
        name: '',
        capa: 'C37',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 38,
        name: '',
        capa: 'C38',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 39,
        name: '',
        capa: 'C39',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 40,
        name: '',
        capa: 'C40',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 41,
        name: '',
        capa: 'C41',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 42,
        name: '',
        capa: 'C42',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 43,
        name: '',
        capa: 'C43',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 44,
        name: '',
        capa: 'C44',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 45,
        name: '',
        capa: 'C45',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 46,
        name: '',
        capa: 'C46',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 47,
        name: '',
        capa: 'C47',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 48,
        name: '',
        capa: 'C48',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 49,
        name: '',
        capa: 'C49',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 50,
        name: '',
        capa: 'C50',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 51,
        name: '',
        capa: 'C51',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 52,
        name: '',
        capa: 'C52',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 53,
        name: '',
        capa: 'C53',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 54,
        name: '',
        capa: 'C54',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 55,
        name: '',
        capa: 'C55',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 56,
        name: '',
        capa: 'C56',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 57,
        name: '',
        capa: 'C57',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 58,
        name: '',
        capa: 'C58',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 59,
        name: '',
        capa: 'C59',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 60,
        name: '',
        capa: 'C60',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 61,
        name: '',
        capa: 'C61',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 62,
        name: '',
        capa: 'C62',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 63,
        name: '',
        capa: 'C63',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 64,
        name: '',
        capa: 'C64',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 65,
        name: '',
        capa: 'C65',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    {
        id: 66,
        name: '',
        capa: 'C66',
        direcao: '',
        sinopse: '',
        nota: '',
        tag1: '',
        tag2: '',
        logo1: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo2: '<li><img src="./assets/img/logos/" alt=""></li>',
        logo3: '',
        logo4: '',
        logo5: '',
    },
    
];

const listContainer = document.querySelector("#container");

function render(filmography){
    let list = '';

    if(filmography.length <= 0){
        list += `<div id="no-project">Nenhum filme encontrado</div>`
    }else{
        filmography.forEach((cod, index) =>{
            list+= `
                <div class="card">
                    <div class="poster">
                        <img src="./assets/img/capas/${cod.capa}.png" alt="">
                    </div>
                    <div class="details">
                        <h3>Direção: ${cod.direcao}</h3>
                        <div class="rating">
                            <i class="fa-solid fa-star"></i>
                            <span>${cod.nota}/10 IMDb</span>
                        </div>
                        <div class="tags">
                            <span>${cod.tag1}</span>
                            <span>${cod.tag2}</span>
                        </div>
                        <div class="sinopse">
                            <p>${cod.sinopse}</p>
                        </div>
                        <div class="streaming">
                            <h4>Onde assistir?</h4>
                            <ul>
                                ${cod.logo1}
                                ${cod.logo2}
                                ${cod.logo3}
                                ${cod.logo4}
                                ${cod.logo5}
                            </ul>
                        </div>
                    </div>
                </div>
            `
        })
    }

    listContainer.innerHTML = list;
};

render(filmography);